# Build image
# $ docker build -t micropython-server-tcp -f Dockerfile.server_tcp .
#
# Run image
# $ docker run -it --rm --name micropython-server-tcp micropython-server-tcp

FROM micropython/unix:v1.18

# use "volumes" in docker-compose file to remove need of rebuilding
# COPY ./ /home
# COPY umodbus /root/.micropython/lib/umodbus

CMD [ "micropython-dev", "-m", "examples/tcp_server_example.py" ]
